:PROPERTIES:
:ID:       70414820-F3B0-429D-84DB-22920D8D7E8F
:END:
#+title: org-mode agenda

- [See also [[id:9676C7B3-2F34-4CE8-87B5-1CDB656D7718][org-super-agenda-mode]].]

- https://orgmode.org/manual/Agenda-Views.html

Due to the way Org works, TODO items, time-stamped items, and tagged headlines can be scattered throughout a file or even a number of files. To get an overview of open action items, or of events that are important for a particular date, this information must be collected, sorted and displayed in an organized way.

The extracted information is displayed in a special agenda buffer. This buffer is read-only, but provides commands to visit the corresponding locations in the original Org files, and even to edit these files remotely.


** agenda files

 #+BEGIN_SRC emacs-lisp
 (org-agenda-files)
 #+END_SRC

 #+RESULTS:

  #+BEGIN_SRC emacs-lisp :results silent

  (defun agenda-todos nil
    (interactive)
    (org-agenda t "t"))

  (define-transient-command t/agenda ()
          "agenda related things"
          ["Actions"
           ("t" "todos" agenda-todos)
           ("l" "agenda files" (lambda () (interactive) (message "%s" org-agenda-files)))
           ("a" "Add file to agenda files" org-agenda-file-to-front)
           ("r" "remove file to agenda files" org-remove-file)])
  #+END_SRC

** WAITING add interactive function to add directory to scan agenda files :urgent:

[[/Users/tangrammer/.emacs.d/straight/repos/org/lisp/org.el::3136][If an entry is a directory, all files in that directory that are matched
by `org-agenda-file-regexp' will be part of the file list.]]
