:PROPERTIES:
:ID:       68707211-4C1F-4562-AE43-2AA0A4E3F21E
:END:
#+title: which-key minor mode

[[id:DF5155DC-47A3-4458-B0BE-8BE3C6B4C03A][help]]

 https://github.com/justbur/emacs-which-key

 =which-key= is a minor mode for Emacs that displays the key bindings
   following your currently entered incomplete command (a prefix) in a
   popup. For example, after enabling the minor mode if you enter =C-x= and wait
   for the default of 1 second the minibuffer will expand with all of the
   available key bindings that follow =C-x= (or as many as space allows given
   your settings).  This includes prefixes like =C-x 8= which are shown in a
   different face. Screenshots of what the popup will look like are included
   below. =which-key= started as a rewrite of [[https://github.com/kai2nenobu/guide-key][guide-key-mode]], but the feature
   sets have diverged to a certain extent.

#+BEGIN_SRC emacs-lisp :results silent
(use-package which-key
  :straight t
  :config (progn
            (which-key-mode)
            (which-key-setup-side-window-right)))



#+END_SRC


**  error: - which-key can’t show keys: There is not enough space based on your settings and frame size.

   customized Which Key Side Window Max Width => 0.6 using following elisp function

 #+BEGIN_SRC untangle
(customize-group 'which-key)
 #+END_SRC


#+BEGIN_SRC emacs-lisp :results silent
(setq which-key-side-window-max-width 0.6)
(setq which-key-side-window-max-height 0.6)
#+END_SRC
